name: Run Test Workflow
on: [workflow_dispatch]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - name: Clone Upstream
        uses: actions/checkout@v3
        with:
          repository: comfyanonymous/ComfyUI
          ref: master
          fetch-depth: 0

      - name: Clone Node
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
          path: custom_nodes/KepPromptLang

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: ${{ matrix.python-version }}

      - name: Cache virtualenv
        uses: actions/cache@v3
        id: cache-venv
        with:
          path: ./.venv/
          key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-${{ matrix.python-version }}-

      - name: Install Requirements
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv ./.venv
          source ./.venv/bin/activate
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
          pip install -r custom_nodes/KepPromptLang/requirements.txt
          pip install huggingface_hub websocket-client

#      - name: Cache SD Checkpoint
#        uses: actions/cache@v3
#        with:
#          path: |
#            models/checkpoints
#          key: ${{ runner.os }}-sd-15-checkpoint

      - name: Check and Download Model
        run: |
          source ./.venv/bin/activate
          python custom_nodes/KepPromptLang/test_files/check_and_download_model.py

      - name: Run in Background
        env:
          PYTHONUNBUFFERED: 1
        run: |
          source ./.venv/bin/activate
          python main.py --cpu &> server.log &
          sleep 10

#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1

      - name: Run Workflow
        run: |
          source ./.venv/bin/activate
          python custom_nodes/KepPromptLang/test_files/run_workflow.py

      - name: Upload Comfy Server Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
            name: comfy-server-log-${{ matrix.python-version }}
            path: server.log

