name: Test With Upstream
on: [workflow_dispatch]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - name: Clone Upstream
        uses: actions/checkout@v3
        with:
          repository: comfyanonymous/ComfyUI
          ref: master
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: ${{ matrix.python-version }}
          # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
          cache: pip

      - name: Clone Node
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
          path: custom_nodes/ClipStuff

      - name: Install Requirements
        run: |
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
          pip install -r custom_nodes/ClipStuff/requirements.txt
          pip install huggingface_hub websocket-client

#      - name: Cache SD Checkpoint
#        uses: actions/cache@v3
#        with:
#          path: |
#            models/checkpoints
#          key: ${{ runner.os }}-sd-15-checkpoint

      - name: Check and Download Model
        env:
          PYTHONUNBUFFERED: 1
        run: |
          python custom_nodes/ClipStuff/test_files/check_and_download_model.py

      - name: Run in Background
        env:
          PYTHONUNBUFFERED: 1
        run: |
          python main.py --cpu &> server.log &
          sleep 10

#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1

      - name: Run Workflow
        run: |
          python custom_nodes/ClipStuff/test_files/run_workflow.py

      - name: Upload Comfy Server Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
            name: comfy-server-log-${{ matrix.python-version }}
            path: server.log

